[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'

[build-system]
requires = ["aequilibrae=0.7.2", "", "", "", "", "", ""]


[tool.poetry.dependencies]
python = "^3.7"
openmatrix = "*"
geopandas = "*"
rasterio = "*"
matplotlib = "*"
pysal = "*"
aequilibrae = "0.7.2"
pyarrow = "*"
pygeos = "*"
tqdm = "*"


[tool.poetry.dev-dependencies]
pytest = "*"
jupyterlab = "*"
Sphinx = "*"
pydata-sphinx-theme = "*"
sphinx_autodoc_annotation = "*"
nbsphinx = "*"
folium = "*"
sphinx-gallery = "*"
ipython_genutils = "*"


[build-system]
requires = ["poetry>=0.12"]
