[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'

[tool.poetry]
name = "tradesman"
version = "0.1"
description = "A Python package for building complete AequilibraE models from open data"
authors = [
    "Renata Akemii",
     "Pedro Camargo <c@margo.co>",
]
maintainers = ["Pedro Camargo <c@margo.co>",]
license = "MIT"


[tool.poetry.dependencies]
python = "~3.9.0"
pysal = "*"
openmatrix = "*"
rasterio = "*"
matplotlib = "*"
aequilibrae = "0.7.4"
pyarrow = "*"
pycountry = "*"
populationsim = "^0.5.1"
tabulate = "^0.8.10"


[tool.poetry.dev-dependencies]
pytest = "*"
jupyterlab = "*"
Sphinx = "*"
pydata-sphinx-theme = "*"
sphinx_autodoc_annotation = "*"
nbsphinx = "*"
folium = "*"
sphinx-gallery = "*"
ipython_genutils = "*"


[build-system]
requires = ["poetry>=0.12"]
