# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.241.1/containers/python-3/.devcontainer/base.Dockerfile

# Python version
FROM mcr.microsoft.com/devcontainers/python:3.12-bullseye

# Install additional OS packages.
RUN apt update -y && apt install -y libsqlite3-mod-spatialite libspatialite-dev
