name: Scheduled Test

on:
  push:
    branches: [develop]
  pull_request:
  schedule:
    - cron: '0 8 1 * *'
  repository_dispatch:
    types: [ custom-event ]

jobs:
  scheduled_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            source .venv/bin/activate
            python3 -m uv pip install git+https://github.com/AequilibraE/aequilibrae.git@develop
            python3 -m pip list
            python3 -m pytest -v
